// <auto-generated />
using System;
using ClassroomManagerAPI.Configs.Infastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ClassroomManagerAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240505212748_lap_code")]
    partial class lap_code
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ClassroomManagerAPI.Entities.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("ClassroomManagerAPI.Entities.Classroom", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ClassNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("FacilityAmount")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastUsed")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ManagerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ManagerId");

                    b.ToTable("Classrooms");

                    b.HasData(
                        new
                        {
                            Id = new Guid("be72d844-8670-48e6-9d6b-859d407f2a5f"),
                            ClassNumber = "401",
                            CreatedAt = new DateTime(2024, 5, 6, 4, 27, 48, 39, DateTimeKind.Local).AddTicks(9581),
                            FacilityAmount = 1,
                            IsDeleted = false,
                            UpdatedAt = new DateTime(2024, 5, 6, 4, 27, 48, 39, DateTimeKind.Local).AddTicks(9581)
                        },
                        new
                        {
                            Id = new Guid("42d228cd-fa56-49ba-b429-f753e34a01f0"),
                            ClassNumber = "402",
                            CreatedAt = new DateTime(2024, 5, 6, 4, 27, 48, 39, DateTimeKind.Local).AddTicks(9587),
                            FacilityAmount = 2,
                            IsDeleted = false,
                            UpdatedAt = new DateTime(2024, 5, 6, 4, 27, 48, 39, DateTimeKind.Local).AddTicks(9587)
                        });
                });

            modelBuilder.Entity("ClassroomManagerAPI.Entities.Facility", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ClassID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ClassID");

                    b.ToTable("Facilities");

                    b.HasData(
                        new
                        {
                            Id = new Guid("9b09d606-e706-4156-b065-2d3962d5ccae"),
                            ClassID = new Guid("be72d844-8670-48e6-9d6b-859d407f2a5f"),
                            Count = 1,
                            CreatedAt = new DateTime(2024, 5, 6, 4, 27, 48, 39, DateTimeKind.Local).AddTicks(9475),
                            IsDeleted = false,
                            Name = "Microphone",
                            Note = "on-built teacher provided Microphone for teaching purposes",
                            Status = "Vacant",
                            UpdatedAt = new DateTime(2024, 5, 6, 4, 27, 48, 39, DateTimeKind.Local).AddTicks(9475),
                            Version = "1.7"
                        },
                        new
                        {
                            Id = new Guid("30d8a6ad-479c-42d7-b0f8-1e8f5270524c"),
                            ClassID = new Guid("42d228cd-fa56-49ba-b429-f753e34a01f0"),
                            Count = 1,
                            CreatedAt = new DateTime(2024, 5, 6, 4, 27, 48, 39, DateTimeKind.Local).AddTicks(9517),
                            IsDeleted = false,
                            Name = "HDMI Cables",
                            Note = "HDMI Cables connected to projector",
                            Status = "Malfunctioned",
                            UpdatedAt = new DateTime(2024, 5, 6, 4, 27, 48, 39, DateTimeKind.Local).AddTicks(9517),
                            Version = "1.4"
                        },
                        new
                        {
                            Id = new Guid("86843949-bb17-41e1-9d44-385d9d8c76c4"),
                            ClassID = new Guid("42d228cd-fa56-49ba-b429-f753e34a01f0"),
                            Count = 1,
                            CreatedAt = new DateTime(2024, 5, 6, 4, 27, 48, 39, DateTimeKind.Local).AddTicks(9520),
                            IsDeleted = false,
                            Name = "Projector",
                            Note = "Projector connected to laptops via HDMI",
                            Status = "Vacant",
                            UpdatedAt = new DateTime(2024, 5, 6, 4, 27, 48, 39, DateTimeKind.Local).AddTicks(9520),
                            Version = "Sony VPL 4K"
                        });
                });

            modelBuilder.Entity("ClassroomManagerAPI.Entities.Report", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ClassID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ReporterID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ClassID");

                    b.HasIndex("ReporterID");

                    b.ToTable("Reports");
                });

            modelBuilder.Entity("ClassroomManagerAPI.Entities.ReportedFacility", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("FacilityID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("ReportID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("FacilityID");

                    b.HasIndex("ReportID");

                    b.ToTable("ReportedFacility");
                });

            modelBuilder.Entity("ClassroomManagerAPI.Entities.Classroom", b =>
                {
                    b.HasOne("ClassroomManagerAPI.Entities.Account", "Manager")
                        .WithMany()
                        .HasForeignKey("ManagerId");

                    b.Navigation("Manager");
                });

            modelBuilder.Entity("ClassroomManagerAPI.Entities.Facility", b =>
                {
                    b.HasOne("ClassroomManagerAPI.Entities.Classroom", "Classroom")
                        .WithMany("Facilities")
                        .HasForeignKey("ClassID");

                    b.Navigation("Classroom");
                });

            modelBuilder.Entity("ClassroomManagerAPI.Entities.Report", b =>
                {
                    b.HasOne("ClassroomManagerAPI.Entities.Classroom", "Classroom")
                        .WithMany("Reports")
                        .HasForeignKey("ClassID");

                    b.HasOne("ClassroomManagerAPI.Entities.Account", "Reporter")
                        .WithMany()
                        .HasForeignKey("ReporterID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Classroom");

                    b.Navigation("Reporter");
                });

            modelBuilder.Entity("ClassroomManagerAPI.Entities.ReportedFacility", b =>
                {
                    b.HasOne("ClassroomManagerAPI.Entities.Facility", "Facility")
                        .WithMany("ReportedFacilities")
                        .HasForeignKey("FacilityID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClassroomManagerAPI.Entities.Report", "Report")
                        .WithMany("ReportedFacilities")
                        .HasForeignKey("ReportID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Facility");

                    b.Navigation("Report");
                });

            modelBuilder.Entity("ClassroomManagerAPI.Entities.Classroom", b =>
                {
                    b.Navigation("Facilities");

                    b.Navigation("Reports");
                });

            modelBuilder.Entity("ClassroomManagerAPI.Entities.Facility", b =>
                {
                    b.Navigation("ReportedFacilities");
                });

            modelBuilder.Entity("ClassroomManagerAPI.Entities.Report", b =>
                {
                    b.Navigation("ReportedFacilities");
                });
#pragma warning restore 612, 618
        }
    }
}
